move2kube:
  containerruntime: docker
  minreplicas: "1"
  services:
    cf-node-redis-app:
      "3000":
        servicetype: Ingress
        urlpath: foo
      containerizationoption:
        - Nodejs-Dockerfile
      enable: true
      port: "3000"
  spawncontainers: false
  target:
    default:
      clustertype: GCP-GKE
      ingress:
        host: myproject.com
        ingressclassname: ""
        tls: ""
    imageregistry:
      namespace: cf-node-redis-app
      quay.io:
        logintype: no authentication
      url: quay.io
  transformers:
    types:
      - ArgoCD
      - Buildconfig
      - CNBContainerizer
      - CloudFoundry
      - ClusterSelector
      - ComposeAnalyser
      - ComposeGenerator
      - ContainerImagesPushScriptGenerator
      - DockerfileDetector
      - DockerfileImageBuildScript
      - DockerfileParser
      - DotNetCore-Dockerfile
      - EarAnalyser
      - EarRouter
      - Golang-Dockerfile
      - Gradle
      - Jar
      - Jboss
      - Knative
      - Kubernetes
      - KubernetesVersionChanger
      - Liberty
      - Maven
      - Nodejs-Dockerfile
      - PHP-Dockerfile
      - Parameterizer
      - Python-Dockerfile
      - ReadMeGenerator
      - Ruby-Dockerfile
      - Rust-Dockerfile
      - Tekton
      - Tomcat
      - WarAnalyser
      - WarRouter
      - WinConsoleApp-Dockerfile
      - WinSLWebApp-Dockerfile
      - WinWebApp-Dockerfile
      - ZuulAnalyser
